# Generated by Django 3.0.6 on 2020-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200721_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='source',
            field=models.URLField(),
        ),
    ]
