# Generated by Django 3.1.2 on 2020-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200721_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
