# Generated by Django 3.1.2 on 2020-11-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20201116_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttech',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projecttech'),
        ),
    ]
